export default {
  'ja': [
    'ある朝目を覚ますと、僕の部屋の冷蔵庫が“魔王”を名乗っていた。',
    '朝起きると、僕の頭が焼きそばパンになっていた。',
    '宇宙人から「冷蔵庫に入ってくれ」と頼まれたのが全ての始まりだった。',
    'トイレから異世界に転移した。またか。',
    '目覚めると、ベッドが巨大なカニになっていた。',
    '家に帰ったら、母が急に『今日からこの家はラーメン屋だから』と言い出した。',
    'いつもの帰り道、ふと思い立って、普段は通らない裏道に入ってみた。',
    '遥か彼方の宇宙船では、現在とある問題が突発している。',
    '昔々、ビッグバンが・・・ 失敗した。',
    '道を歩いていたら、「押すなよ！絶対押すなよ」と書かれたボタンを見つけた。',
    'ドアの下に挟まっていた白い封筒には、ただ一言「きみが選ばれた」と書かれていた。',
    '名前も、住んでいた場所も、何もかもが思い出せないまま、僕は白い部屋で目を覚ました。',
    '授業中、窓の外ばかり見ていた。今日こそ、あのビルの屋上に立つ“黒い影”の正体を確かめようと思った。',
    '放課後、カバンが少し重かった。でも中身は、いつも通り教科書と筆箱と――昨日拾った“あれ”のはずだった。',
    '公園のベンチでパンを食べていると、いつものハトが寄ってきた。',
    'スマホを手に取ると、通知が200件来ていた。',
    '通学路の途中にある古い神社の前で、ふと足を止めた。',
    '教室のドアを開けたとき、みんなの視線が一斉にこちらを向いた。',
    'いつもの電車に乗っているはずなのに、降りるべき駅が見当たらなかった。',
  ],
  'en': [
    'One morning, I woke up to find my refrigerator calling itself the “Demon King.”',
    'It all started when an alien asked me to “get inside the fridge.”',
    'I was transported to another world from the bathroom. Again.',
    'I got isekai\'d from the bathroom. Again.',
    'I was eating bread on a park bench when the usual pigeons came to me.',
    'After school, my bag felt heavier than usual. Inside, as always, were my textbooks and pencil case — but also “that thing” I found yesterday.',
    'I was on my usual train, but the station where I was supposed to get off was nowhere to be seen.',
    'During class, I kept looking out the window. Today, I was determined to find out who the “black figure” standing on that building’s rooftop really was.',
    'On my usual way home, I suddenly decided to take a path I normally never use.',
    'While walking down the street, I found a button with a sign that said, “Don’t push! Absolutely do NOT push.”',
    'I woke up in a white room, remembering neither my name nor where I lived.',
    'On my way to school, I paused in front of an old shrine I’d never really noticed before.',
    'When I opened the classroom door, everyone’s eyes turned to me all at once.',
    'I picked up my phone to find 200 notifications waiting for me.',
    'There was a white envelope stuck under the door with only one line written inside: “You have been chosen.”',
    'Far away on a spaceship in deep space, a sudden problem has just occurred.',
    'Long ago, the Big Bang… failed.',
    'When I woke up, my bed had become a giant crab.',
    'I came home to find my mom suddenly saying, “From today, this house is a taco stand.”'
  ]
}